// https://docs.google.com/spreadsheets/d/17kUJoGJvZJlHQcAi62mVN6Td2tBXAZ2acly_VmeUse0/edit#gid=0

export const SCREENS = {
  ACTIONS_BY_USER: "ActionsByUser",
  ALL_TRANSACTIONS: "AllTransactions",
  API_AUTHORIZATION: "ApiAuthorization",
  API_AUTHORIZATION_PERMISSIONS: "ApiAuthorizationPermissions",
  APPEARANCE: "Appearance",
  BALANCE_HISTORY: "BalanceHistory",
  BITWALA: "BitWala",
  BIOMETRICS_AUTHENTICATION: "BiometricAuthentication",
  BORROW_BANK_ACCOUNT: "BorrowBankAccount",
  BORROW_CALCULATOR_SCREEN: "BorrowCalculatorScreen",
  BORROW_CHOOSE_LOAN: "BorrowChooseLoan",
  BORROW_COLLATERAL: "BorrowCollateral",
  BORROW_ENTER_AMOUNT: "BorrowEnterAmount",
  BORROW_LANDING: "BorrowLanding",
  BORROW_LOAN_CONFIRM: "BorrowLoanConfirm", // remove screen - not using any more
  BORROW_LOAN_OPTION: "BorrowLoanOption",
  BORROW_LOAN_TERM: "BorrowLoanTerm",
  CAMERA_SCREEN: "CameraScreen",
  CELLPHONE_ENTER: "CellphoneEnter",
  CELLPHONE_VERIFY: "CellphoneVerify",
  CEL_PAY_CHOOSE_FRIEND: "CelPayChooseFriend",
  CEL_PAY_ENTER_AMOUNT: "CelPayEnterAmount",
  CEL_PAY_LANDING: "CelPayLanding",
  CEL_PAY_MESSAGE: "CelPayMessage",
  CELSIUS_LOADING_SCREEN: "CelsiusLoadingScreen", // NOTE: not calling in js code
  CHANGE_PASSWORD: "ChangePassword",
  CHANGE_PIN: "ChangePin",
  CHOOSE_MARGIN_COLLATERAL_COIN: "ChooseMarginCollateralCoin", // NOTE: do we use this?
  CHOOSE_PAYMENT_METHOD: "ChoosePaymentMethod",
  COIN_DETAILS: "CoinDetails",
  COMMUNITY: "Community",
  CONFIRM_CAMERA: "ConfirmCamera",
  CONFIRM_YOUR_LOAN: "ConfirmYourLoan",
  DEPOSIT: "Deposit",
  FORGOT_PASSWORD: "ForgotPassword",
  GET_COINS_ENTER_AMOUNT: "GetCoinsEnterAmount",
  GET_COINS_GEM: "GetCoinsGem",
  GET_COINS_LANDING: "GetCoinsLanding",
  GET_COINS_TRANSACTION_DETAILS: "GetCoinsTransactionDetails",
  HODL_DEACTIVATION_CODE: "HodlDeactivationCode",
  HODL_INFO_CHECK_BOXES: "HODLInfoCheckboxes",
  HODL_LANDING: "HodlLanding",
  HODL_VIEW_CODE: "HODLViewCode",
  HOME: "Home",
  INTEREST_CALCULATOR_SCREEN: "InterestCalculatorScreen",
  INTEREST_PAYMENT_SETTINGS: "InterestPaymentSettings",
  INTEREST_RATES: "InterestRates",
  KYC_ADDRESS_INFO: "KYCAddressInfo",
  KYC_ADDRESS_PROOF: "KYCAddressProof",
  KYC_CHECK_PHOTOS: "KYCCheckPhotos", // note: do we use this?
  KYC_CHECK_UTILITY_BILL: "KYCCheckUtilityBill", // note: do we use this?
  KYC_FINAL_REJECTION: "KYCFinalRejection",
  KYC_PRIME_TRUST_TOU: "KYCPrimeTrustToU",
  KYC_PROFILE_DETAILS: "KYCProfileDetails",
  KYC_TAXPAYER: "KYCTaxpayer",
  KYC_VERIFY_IDENTITY: "KYCVerifyIdentity",
  LOADING_SCREEN: "LoadingScreen", // NOTE: not calling in js code
  LOAN_PAYMENT_COIN: "LoanPaymentCoin",
  LOAN_PAYMENT_HISTORY: "LoanPaymentHistory",
  LOAN_PAYMENT_LIST: "LoanPaymentList",
  LOAN_PREPAYMENT_PERIOD: "LoanPrepaymentPeriod",
  LOAN_REQUEST_DETAILS: "LoanRequestDetails",
  LOAN_SETTINGS: "LoanSettings",
  LOAN_TERMS_OF_USE: "LoanTermsOfUse",
  LOGIN: "Login",
  LOGIN_LANDING: "LoginLanding",
  LOYALTY_PROGRAM: "LoyaltyProgram",
  MAINTENANCE: "Maintenance",
  MY_CEL: "MyCel",
  NOTIFICATION_SETTINGS: "NotificationsSettings", // NOTE: do we use this?
  PASSWORD_BREACHED: "PasswordBreached",
  PAYMENT_CEL: "PaymentCel",
  PERSONAL_INFORMATION: "PersonalInformation",
  PRINCIPAL_PAYMENT: "PrincipalPayment",
  PRINCIPAL_PAYMENT_TYPE: "PrincipalPaymentType",
  PROFILE: "Profile",
  PROFILE_PHOTO: "ProfilePhoto", // NOTE: to remove screen?
  QR_SCANNER: "QRScanner",
  REGISTER_INITIAL: "RegisterInitial",
  REGISTER_SET_PIN: "RegisterSetPin",
  SECURITY_FIX_NOW: "SecurityFixNow",
  SECURITY_OVERVIEW: "SecurityOverview",
  SECURITY_SETTINGS: "SecuritySettings",
  SELECT_COIN: "SelectCoin",
  SELECT_COUNTRY: "SelectCountry",
  SELECT_STATE: "SelectState",
  SIMPLEX: "Simplex",
  SIX_DIGIT_PIN_EXPLANATION: "SixDigitPinExplanation",
  SPLASH_SCREEN: "SplashScreen",
  STATIC_SCREEN: "StaticScreen", // NOTE: not used with navigateTo\
  STORYBOOK: "Storybook",
  SUPPORT: "Support",
  TOO_MANY_REQUESTS: "TooManyRequests",
  TRANSACTION_DETAILS_CELPAY: "TransactionDetailsCelPay",
  TRANSACTION_DETAILS_DEPOSIT: "TransactionDetailsDeposits",
  TRANSACTION_DETAILS_GENERAL: "TransactionDetailsGeneral",
  TRANSACTION_DETAILS_INTEREST: "TransactionDetailsInterest",
  TRANSACTION_DETAILS_LOANS: "TransactionDetailsLoans",
  TRANSACTION_DETAILS_REWARDS: "TransactionDetailsRewards",
  TRANSACTION_DETAILS_WITHDRAW: "TransactionDetailsWithdraw",
  TRANSACTION_INTERSECTION: "TransactionsIntersection",
  TRANSACTION_ON_HOLD: "TransactionsOnHold", // NOTE: do we use this?
  TWO_FA_AUTH_APP_CONFIRMATION_CODE: "TwoFaAuthAppConfirmationCode",
  TWO_FACTOR_SETTINGS: "TwoFactorSettings",
  VERIFY_PROFILE: "VerifyProfile",
  WALLET_INTEREST: "WalletInterest",
  WALLET_LANDING: "WalletLanding",
  WALLET_SETTINGS: "WalletSettings",
  WELCOME: "Welcome",
  WIRING_BANK_INFORMATION: "WiringBankInformation",
  WITHDRAW_ADDRESS_LABEL: "WithdrawAddressLabel",
  WITHDRAW_ADDRESS_OVERVIEW: "WithdrawAddressOverview",
  WITHDRAW_CONFIRM: "WithdrawConfirm",
  WITHDRAW_CONFIRM_ADDRESS: "WithdrawConfirmAddress",
  WITHDRAW_CREATE_ADDRESS: "WithdrawCreateAddress",
  WITHDRAW_ENTER_AMOUNT: "WithdrawEnterAmount",
  WITHDRAW_NEW_ADDRESS_SETUP: "WithdrawNewAddressSetup",
  INTEREST_PAYMENT_OVERVIEW: "InterestPaymentOverviewScreen",
  MARGIN_CALL_OVERVIEW_SCREEN: "MarginCallOverviewScreen",
  SINGLE_MARGIN_CALL_SCREEN: "SingleMarginCallScreen",
  EXTEND_LOAN: "ExtendLoanScreen",
};
