import { SCREENS } from "./SCREENS";

const KEYBOARD_TYPE = {
  DEFAULT: "default",
  NUMERIC: "numeric",
  EMAIL: "email-address",
  PHONE: "phone-pad",
  NUMBER_PAD: "number-pad",
};

const MODALS = {
  API_KEY_REVOKE_MODAL: "API_KEY_REVOKE_MODAL",
  CELPAY_RECEIVED_MODAL: "CELPAY_RECEIVED_MODAL",
  CHANGE_WITHDRAWAL_ADDRESS_MODAL: "CHANGE_WITHDRAWAL_ADDRESS_MODAL", // new modal
  CONFIRM_WITHDRAWAL_ADDRESS_MODAL: "CONFIRM_WITHDRAWAL_ADDRESS_MODAL", // new modal
  CREATE_NEW_ACCOUNT_MODAL: "CREATE_NEW_ACCOUNT_MODAL", // new modal - not binded in new flow
  DEPOSIT_INFO_MODAL: "DEPOSIT_INFO_MODAL",
  DESTINATION_TAG_MODAL: "DESTINATION_TAG_MODAL", // <-- not moved checked
  GENERATE_API_KEY_MODAL: "GENERATE_API_KEY_MODAL",
  KYC_REJECTION_REASONS_MODAL: "KYC_REJECTION_REASONS_MODAL",
  LOAN_ALERT_MODAL: "LOAN_ALERT_MODAL",
  LOAN_APPLICATION_SUCCESS_MODAL: "LOAN_APPLICATION_SUCCESS_MODAL",
  LOAN_CANCEL_MODAL: "LOAN_CANCEL_MODAL",
  LOSE_TIER_MODAL: "LOSE_TIER_MODAL",
  MEMO_ID_MODAL: "MEMO_ID_MODAL",
  MY_CEL_LOYALTY_CALCULATOR_MODAL: "MY_CEL_LOYALTY_CALCULATOR_MODAL",
  PREPAY_DOLLAR_INTEREST_MODAL: "PREPAY_DOLLAR_INTEREST_MODAL",
  PREPAYMENT_SUCCESSFUL_MODAL: "PREPAYMENT_SUCCESSFUL_MODAL", // new modal
  REFERRAL_RECEIVED_MODAL: "REFERRAL_RECEIVED_MODAL", // <-- not moved not using
  REFERRAL_SEND_MODAL: "REFERRAL_SEND_MODAL",
  REGISTER_PROMO_CODE_MODAL: "REGISTER_PROMO_CODE_MODAL",
  SSN_MODAL: "SSN_MODAL",
  TRANSACTION_FILTER_MODAL: "TRANSACTION_FILTER_MODAL", // new modal
  VERIFY_AUTHAPP_MODAL: "VERIFY_AUTHAPP_MODAL",
  WITHDRAW_INFO_MODAL: "WITHDRAW_INFO_MODAL",
  WITHDRAW_WARNING_MODAL: "WITHDRAW_WARNING_MODAL",
  INTEREST_DUE_MODAL: "INTEREST_DUE_MODAL",
  CELPAY_INFO_MODAL: "CELPAY_INFO_MODAL",
  GET_COINS_INFO_MODAL: "GET_COINS_INFO_MODAL",
  GET_COINS_CONFIRM_MODAL: "GET_COINS_CONFIRM_MODAL",
  HODL_MODE_MODAL: "HODL_MODE_MODAL",
  SEPARATOR_INFO_MODAL: "SEPARATOR_INFO_MODAL",
  BANK_TO_THE_FUTURE_MODAL: "BANK_TO_THE_FUTURE_MODAL",
  CONFIRM_INTEREST_PAYMENT: "CONFIRM_INTEREST_PAYMENT",
  DOLLAR_PAYMENT_MODAL: "DOLLAR_PAYMENT_MODAL",
  INTEREST_REMINDER_MODAL: "INTEREST_REMINDER_MODAL",
  CONFIRM_INTEREST_PREPAYMENT: "CONFIRM_INTEREST_PREPAYMENT",
  CONFIRM_RESPONSE_MODAL: "CONFIRM_RESPONSE_MODAL",
  MARGIN_CALL_MODAL: "MARGIN_CALL_MODAL",
  TOP_UP_MODAL: "TOP_UP_MODAL",
  MARGIN_CALL_CONFIRM: "MARGIN_CALL_CONFIRM",
  POA_WARNING_MODAL: "POA_WARNING_MODAL",
  INTRODUCE_NEW_THEME_MODAL: "INTRODUCE_NEW_THEME_MODAL",
  BIOMETRICS_AUTHENTICATION_MODAL: "BIOMETRICS_AUTHENTICATION_MODAL",
  BIOMETRICS_NOT_RECOGNIZED_MODAL: "BIOMETRICS_NOT_RECOGNIZED_MODAL",
  BIOMETRICS_ACTIVATE_FINGERPRINT_MODAL:
    "BIOMETRICS_ACTIVATE_FINGERPRINT_MODAL",
  PICKER_MODAL: "PICKER_MODAL",
};

const INITIAL_ROUTE = SCREENS.SPLASH_SCREEN;

const THEMES = {
  LIGHT: "light",
  DARK: "dark",
  UNICORN: "unicorn",
};

const EMPTY_STATES = {
  USER_CLEARED: "USER_CLEARED",

  NON_VERIFIED_CELPAY: "NON_VERIFIED_CELPAY",
  NON_VERIFIED_BORROW: "NON_VERIFIED_BORROW",
  NON_VERIFIED_DEPOSIT: "NON_VERIFIED_DEPOSIT",
  NON_VERIFIED_WITHDRAW: "NON_VERIFIED_WITHDRAW",
  NON_VERIFIED_INTEREST: "NON_VERIFIED_INTEREST",
  NON_VERIFIED_GET_COINS: "NON_VERIFIED_GET_COINS",

  VERIFICATION_IN_PROCESS_DEPOSIT: "VERIFICATION_IN_PROCESS_DEPOSIT",
  VERIFICATION_IN_PROCESS_CELPAY: "VERIFICATION_IN_PROCESS_CELPAY",
  VERIFICATION_IN_PROCESS_WITHDRAW: "VERIFICATION_IN_PROCESS_WITHDRAW",
  VERIFICATION_IN_PROCESS_GET_COINS: "VERIFICATION_IN_PROCESS_GET_COINS",

  ZERO_INTEREST: "ZERO_INTEREST",
  NO_SSN_INTEREST: "NO_SSN_INTEREST",
  NO_LOANS: "NO_LOANS",
  BORROW_NOT_ENOUGH_FUNDS: "BORROW_NOT_ENOUGH_FUNDS",

  NO_WITHDRAWAL_ADDRESSES: "NO_WITHDRAWAL_ADDRESSES",
  MAINTENANCE: "MAINTENANCE",
  COMPLIANCE: "COMPLIANCE",
  NO_CONTACTS: "NO_CONTACTS",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  NO_TRANSACTIONS: "NO_TRANSACTIONS",
  BUY_COINS_COMPLIANCE: "BUY_COINS_COMPLIANCE",

  HODL_MODE_WARNING_WITHDRAW: "HODL_MODE_WARNING_WITHDRAW",
  HODL_MODE_WARNING_CELPAY: "HODL_MODE_WARNING_CELPAY",
  HODL_MODE_ACTIVE: "HODL_MODE_ACTIVE",
  CHECK_YOUR_EMAIL: "CHECK_YOUR_EMAIL",
  HODL_MODE_BACKOFFICE: "HODL_MODE_BACKOFFICE",
  HODL_MODE_PENDING_DEACTIVATION: "HODL_MODE_PENDING_DEACTIVATION",

  SIX_DIGITS_PIN_UPGRADE: "SIX_DIGITS_PIN_UPGRADE",
};

const KEYPAD_PURPOSES = {
  WITHDRAW: "WITHDRAW",
  CELPAY: "CELPAY",
  VERIFICATION: "VERIFICATION",
  AMOUNT: "AMOUNT",
  INTEREST_CALCULATOR: "INTEREST_CALCULATOR",
  BORROW: "BORROW",
  BUY_COINS: "BUY_COINS",
};

const PHONES_WITH_CUSTOM_KEYPAD = [
  "iPhone X",
  // 'Simulator',
];

const HIGHLIGHTED_COUNTRIES = [
  "Canada",
  "Germany",
  "United Kingdom",
  "Australia",
  "United States",
];

const WALLET_LANDING_VIEW_TYPES = {
  GRID: "grid",
  LIST: "list",
};

const FAB_TYPE = ["main", "support", "hide"];

const WELCOME_MESSAGES = [
  {
    title: "Rewards Income",
    text:
      "Make your Mondays a whole lot more interesting. Deposit coins and receive weekly interest payments directly to your Celsius wallet.",
  },
  {
    title: "Crypto is the New Collateral",
    text:
      "Crypto-backed loans give you access to the cash you need at rates you deserve without selling your coins! ",
  },
  {
    title: "No Fees, No Worries",
    text:
      "CelPay is the easiest way to send and receive crypto instantly - without the fees.",
  },
  {
    title: "Unity in Community",
    text:
      "Celsius’s promise is to only act in the best interest of our community by offering unmatched financial services that are safe, secure, and rewarding.",
  },
  {
    title: "Join the CEL-ebration!",
    text: `Get the most out of your Celsius app by earning in CEL! Earning interest in the CEL token gets you up to 30% more interest.`,
  },
];

const COIN_CARD_TYPE = {
  COLLATERAL_COIN_CARD: "COLATERAL_COIN_CARD",
  PRINCIPAL_PAYMENT_COIN_CARD: "PRINCIPAL_PAYMENT_COIN_CARD",
  LOAN_PAYMENT_COIN_CARD: "LOAN_PAYMENT_COIN_CARD",
  MARGIN_COLLATERAL_COIN_CARD: "MARGIN_COLLATERAL_COIN_CARD",
};

const LOAN_PAYMENT_REASONS = {
  INTEREST: "INTEREST",
  MANUAL_INTEREST: "MANUAL_INTEREST",
  INTEREST_PREPAYMENT: "INTEREST_PREPAYMENT",
  PRINCIPAL: "PRINCIPAL",
  MARGIN_CALL: "MARGIN_CALL",
  COLLATERAL: "COLLATERAL",
};

const LOAN_ALERTS = {
  INTEREST_ALERT: "INTEREST_ALERT",
  PRINCIPAL_ALERT: "PRINCIPAL_ALERT",
  MARGIN_CALL_ALERT: "MARGIN_CALL_ALERT",
};

const LOAN_FILTER_ITEMS = [
  "ALL",
  "ACTIVE",
  "PENDING",
  "COMPLETED",
  "REFINANCED",
  "CANCELED",
];

const HODL_STATUS = {
  ACTIVATED: "Activated",
  DEACTIVATED: "Deactivated",
  PENDING_DEACTIVATION: "Pending Deactivate",
  INACTIVE: "Inactive",
};

const TRANSACTION_FILTER_DATE = [
  {
    title: "Anytime",
    value: null,
  },
  {
    title: "Last Day",
    value: "day",
  },
  {
    title: "Last Week",
    value: "week",
  },
  {
    title: "Last Month",
    value: "month",
  },
  {
    title: "Last Three Months",
    value: "threeMonths",
  },
  {
    title: "Last Six Months",
    value: "sixMonths",
  },
  {
    title: "Last 12 months",
    value: "lastYear",
  },
  {
    title: "Year to Date",
    value: "yearToDate",
  },
  {
    title: "Previous year",
    value: "prevYear",
  },
];

const TRANSACTION_FILTER_TYPE = [
  {
    title: "All Transactions",
    value: null,
  },
  {
    title: "Rewards",
    value: "interest",
    icon: "TransactionInterest",
  },
  {
    title: "Deposits",
    value: "received",
    icon: "TransactionReceived",
  },
  {
    title: "CelPay",
    value: "celpay",
    icon: "TransactionCelpay",
  },
  {
    title: "Loans",
    value: "loan",
    icon: "TransactionLoan",
  },
  {
    title: "Withdrawals",
    value: "withdraw",
    icon: "TransactionSent",
  },
];

const CEL_PAY_TYPES = {
  LINK: "LINK",
  FRIEND: "FRIEND",
};

const BIOMETRIC_TYPES = {
  TOUCH_ID: "TouchID",
  FACE_ID: "FaceID",
  BIOMETRICS: "Biometrics",
};

const BIOMETRIC_TEXT = {
  TOUCH_ID: "Touch ID",
  BIOMETRICS: "Biometric",
  FINGERPRINT: "Fingerprint",
  FACE_ID: "Face ID",
};

const BIOMETRIC_ERRORS = {
  TOO_MANY_ATTEMPTS_SENSOR_DISABLED:
    "Error: Too many attempts. Fingerprint sensor disabled",
  TOO_MANY_ATTEMPTS: "Too many attempts. Try again later.",
  KEY_PERMANENTLY_INVALIDATED:
    "Error generating signature: Key permanently invalidated",
  NO_IDENTITIES_ARE_ENROLLED:
    'Error Domain=com.apple.LocalAuthentication Code=-7 "No identities are enrolled." UserInfo={NSLocalizedDescription=No identities are enrolled.}',
  ERROR_GENERATING_PUBLIC_KEYS: "Error generating public private keys",
  AUTHENTICATION_CANCELLED: "Authentication cancelled",
  KEY_NOT_FOUND: "Key not found: -128",
  NO_HARDWARE: "BIOMETRIC_ERROR_NO_HARDWARE",
  HW_UNAVAILABLE: "BIOMETRIC_ERROR_HW_UNAVAILABLE",
  NONE_ENROLLED: "BIOMETRIC_ERROR_NONE_ENROLLED",
};

export {
  KEYBOARD_TYPE,
  MODALS,
  INITIAL_ROUTE,
  THEMES,
  EMPTY_STATES,
  KEYPAD_PURPOSES,
  PHONES_WITH_CUSTOM_KEYPAD,
  HIGHLIGHTED_COUNTRIES,
  FAB_TYPE,
  WALLET_LANDING_VIEW_TYPES,
  WELCOME_MESSAGES,
  COIN_CARD_TYPE,
  LOAN_PAYMENT_REASONS,
  LOAN_ALERTS,
  LOAN_FILTER_ITEMS,
  TRANSACTION_FILTER_DATE,
  TRANSACTION_FILTER_TYPE,
  CEL_PAY_TYPES,
  HODL_STATUS,
  BIOMETRIC_TYPES,
  BIOMETRIC_TEXT,
  BIOMETRIC_ERRORS,
};
